language: node_js
node_js:
  - "node"
env:
  global:
    - CXX=g++-4.8
    - env=test
addons:
  hosts:
    - travis.serandives.com
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
install:
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-3.4.7.tgz
  - tar xzf mongodb-linux-x86_64-3.4.7.tgz
  - ${PWD}/mongodb-linux-x86_64-3.4.7/bin/mongod --version