language: node_js
node_js:
  - "node"
env:
  global:
    - CXX=g++-4.8
    - ENV=travis
addons:
  hosts:
    - travis.serandives.com
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - mongodb-upstart
      - mongodb-3.0-precise
    packages:
      - g++-4.8
      - mongodb-org-server
      - mongodb-org-shell